# Generated by Django 4.1 on 2022-12-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_makanan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
